#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Sensor, in1,    gyro,           sensorGyro)
#pragma config(Sensor, in2,    powerExpander,  sensorAnalog)
#pragma config(Sensor, dgtl1,  flywheelRot,    sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  leftDrive,      sensorQuadEncoder)
#pragma config(Sensor, dgtl8,  rightDrive,     sensorQuadEncoder)
#pragma config(Sensor, dgtl11, ballDetector,   sensorSONAR_cm)
#pragma config(Motor,  port1,           Uptake,        tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           FlywheelA,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           DriveFR,       tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           DriveFL,       tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           CapFlipper,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Intake,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           DriveBL,       tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port8,           DriveBR,       tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           FlywheelB,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Com	petition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/


// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

// Main competition background code...do not modify!
#include "Vex_Competition_Includes.c"

#include "lib\util.c"
#include "hal.c"

#include "lib\lcd.c"
#include "lib\motor.c"
#include "lib\pid.c"
#include "lib\auton.c"

void pre_auton() {
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks
  // running between Autonomous and Driver controlled modes. You will need to
  // manage all user created tasks if set to false.
  bStopTasksBetweenModes = false;
  bDisplayCompetitionStatusOnLcd = false;

  SensorType[gyro] = sensorNone;
  lcdStartup();
  SensorType[gyro] = sensorGyro;
  wait1Msec(2000);

  // Clear flywheel Quad Encoder
  SensorValue[flywheelRot] = 0;

  // Clear Drive Encoders
  SensorValue[leftDrive] = 0;
  SensorValue[rightDrive] = 0;

  startTask(lcdDebug);

}

task autonomous() {

	startTask(hardwareAbstractionLayer);
  startTask(lcdDebug);

  autonOne();
}

task usercontrol() {

  startTask(hardwareAbstractionLayer);
  startTask(lcdDebug);

  while (true) {
    wait1Msec(20);
  }

}
